events {}

http {
    server {
        # Слухаємо порт 80 (стандартний HTTP) всередині контейнера
        listen 80;

        location / {
            # Проксуємо запити на сервіс "web" (ім'я з docker-compose)
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
